Inspecting the datasets

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
daily = pd.read_csv("data/anonym_aamos00_dailyquestionnaire.csv")
weekly = pd.read_csv("data/anonym_aamos00_weeklyquestionnaire.csv")
peakflow = pd.read_csv("data/anonym_aamos00_peakflow.csv")
patient = pd.read_csv("data/anonym_aamos00_patient_info.csv")

print("Daily:", daily.shape)
print("Weekly:", weekly.shape)
print("Peak flow:", peakflow.shape)
print("Patient:", patient.shape)

Daily: (1583, 8)
Weekly: (324, 12)
Peak flow: (1516, 6)
Patient: (22, 28)

In [ ]:
print("DAILY")
print(daily.columns.tolist())

print("\nWEEKLY")
print(weekly.columns.tolist())

print("\nPEAK FLOW")
print(peakflow.columns.tolist())

print("\nPATIENT")
print(patient.columns.tolist())

DAILY
['user_key', 'date', 'daily_night_symp', 'daily_day_symp', 'daily_limit_activity', 'daily_prev_inhaler', 'daily_relief_inhaler', 'daily_triggers']

WEEKLY
['user_key', 'date', 'weekly_night_symp', 'weekly_day_symp', 'weekly_limit_activity', 'weekly_short_breath', 'weekly_wheeze', 'weekly_relief_inhaler', 'weekly_doc', 'weekly_hospital', 'weekly_er', 'weekly_oral']

PEAK FLOW
['user_key', 'date', 'hour', 'pef_max', 'pefs', 'morning']

PATIENT
['user_key', 'sex', 'age_range', 'bmi_range', 'age_diagnosed_range', 'max_pef_expected', 'smoker', 'pack_years', 'race', 'severity', 'pef_best', 'n_inhalers', 'region', 'nation', 'phase2_start', 'daily_start_date', 'weekly_start_date', 'miband_start_date', 'position_start_date', 'pef_start_date', 'inhaler_start_date', 'daily_end_date', 'weekly_end_date', 'miband_end_date', 'position_end_date', 'pef_end_date', 'inhaler_end_date', 'phase2_end']

In [6]:
display(daily.head())
display(weekly.head())
display(peakflow.head())
display(patient.head())

,user_key,date,daily_night_symp,daily_day_symp,daily_limit_activity,daily_prev_inhaler,daily_relief_inhaler,daily_triggers
0,113,0,True,True,False,2,5,"5,9"
1,113,1,False,False,False,2,3,"5,9"
2,113,2,False,True,False,2,5,"5,9"
3,113,3,False,False,False,2,1,"5,12"
4,113,4,False,True,False,2,3,"5,9"

,user_key,date,weekly_night_symp,weekly_day_symp,weekly_limit_activity,weekly_short_breath,weekly_wheeze,weekly_relief_inhaler,weekly_doc,weekly_hospital,weekly_er,weekly_oral
0,113,1,2.0,3.0,1.0,2,2,3,-4,0,0,2.0
1,113,7,2.0,3.0,2.0,2,2,2,-5,0,0,2.0
2,113,14,5.0,5.0,5.0,4,4,5,"-1,-3",0,-2,3.0
3,113,22,4.0,5.0,4.0,4,2,4,-3,0,0,3.0
4,113,28,3.0,3.0,3.0,3,2,3,0,0,0,3.0

   user_key  date  hour  pef_max         pefs  morning
0       113     1     7      469   469|99|144     True
1       113     1    15      310  310|174|175    False
2       113     3    13      290  249|290|207     True
3       113    40    16      557   71|557|525    False
4       190     6     7      333  333|307|150     True

,user_key,sex,age_range,bmi_range,age_diagnosed_range,max_pef_expected,smoker,pack_years,race,severity,...,position_start_date,pef_start_date,inhaler_start_date,daily_end_date,weekly_end_date,miband_end_date,position_end_date,pef_end_date,inhaler_end_date,phase2_end
0,113,female,30-39yo,Obesity,7-11yo,485,Never (<100 cigarettes in lifetime),0.00,White,Severe,...,1,1.0,0.0,183,183,183.0,183,40.0,177.0,183
1,190,male,50+yo,Pre-obesity,19+yo,575,Previous,18.75,White,Severe,...,1,6.0,1.0,183,182,148.0,183,183.0,19.0,183
2,217,female,30-39yo,Obesity,19+yo,495,Previous,6.30,White,Moderate,...,0,0.0,1.0,1,0,1.0,1,0.0,1.0,1
3,278,female,18-29yo,Pre-obesity,12-18yo,495,Previous,1.20,White,Moderate,...,0,NaN,-20.0,15,15,15.0,13,NaN,106.0,106
4,294,female,50+yo,Obesity,0-6yo,455,Never (<100 cigarettes in lifetime),0.00,White,Moderate,...,0,0.0,-5.0,183,182,183.0,183,183.0,184.0,184

Understanding the variables better by digging into the data dictionary.

In [16]:
weekly_oral_info = data_dictionary[
    data_dictionary["Variable Name"].astype(str).str.lower() == "weekly_oral"
]

display(weekly_oral_info.T)

                                                              158
Data Source                                                   NaN
Variable Name                                         weekly_oral
Variable Label  Did you use systemic corticosteroids (Predniso...
Answer Details  Possible values: 1 = No, 2 = Yes, but no more ...
Data type                                                 Numeric
Format                                                          N

so basically weekly_oral indicates whether the patient took systemic corticosteroids in the last week.

In [ ]:
print(weekly["weekly_oral"].value_counts().sort_index())

weekly_oral
1.0    241
2.0     39
3.0     43
Name: count, dtype: int64

In [21]:
#total 323 observations of weekly_oral

print(weekly[[
    "weekly_night_symp",
    "weekly_day_symp",
    "weekly_limit_activity",
    "weekly_short_breath",
    "weekly_wheeze"
]].describe())

       weekly_night_symp  weekly_day_symp  weekly_limit_activity  \
count         148.000000       291.000000             209.000000
mean            2.568919         5.364261               3.913876
std             1.737417         2.115125               2.221453
min             1.000000         1.000000               1.000000
25%             1.000000         4.000000               2.000000
50%             2.000000         7.000000               3.000000
75%             3.000000         7.000000               6.000000
max             7.000000         7.000000               7.000000

       weekly_short_breath  weekly_wheeze
count           324.000000     324.000000
mean              2.398148       1.851852
std               0.930460       0.867167
min               1.000000       1.000000
25%               2.000000       1.000000
50%               2.000000       2.000000
75%               3.000000       2.000000
max               5.000000       5.000000

In [24]:
# Inspect the value distribution of weekly symptom variables,

for col in [
    "weekly_night_symp",
    "weekly_day_symp",
    "weekly_limit_activity",
    "weekly_short_breath",
    "weekly_wheeze"
]:
    print(f"\n--- {col} ---")
    print(weekly[col].value_counts(dropna=False).sort_index())

--- weekly_night_symp ---
weekly_night_symp
1.0     53
1.2      1
2.0     32
3.0     27
4.0     17
5.0      5
6.0      3
7.0     10
NaN    176
Name: count, dtype: int64

--- weekly_day_symp ---
weekly_day_symp
1.0     22
2.0     27
3.0     21
4.0     15
5.0     29
6.0     22
7.0    155
NaN     33
Name: count, dtype: int64

--- weekly_limit_activity ---
weekly_limit_activity
1.0     36
2.0     37
3.0     34
4.0     16
5.0     24
6.0     12
7.0     50
NaN    115
Name: count, dtype: int64

--- weekly_short_breath ---
weekly_short_breath
1     37
2    177
3     62
4     40
5      8
Name: count, dtype: int64

--- weekly_wheeze ---
weekly_wheeze
1    127
2    138
3     41
4     16
5      2
Name: count, dtype: int64